---
feedOutputs:
  - id: feedItemAttributes
    jobName: feedItemAttributesV4
    description: "This feed contains the mapping of item attributes and their values to individual item ids."
    schema:
      - { columnName: item_id, columnType: string }
      - { columnName: idx, columnType: integer }
      - { columnName: value, columnType: string }

  - id: feedReturns
    jobName: feedReturnsV4
    description: "This feed contains all returns processed for a given day"
    schema:
      - { columnName: order_id, columnType: string }
      - { columnName: item_id, columnType: string }
      - { columnName: product_id, columnType: string }
      - { columnName: seller, columnType: string }
      - { columnName: quantity, columnType: integer }
      - { columnName: return_timestamp, columnType: string }
      - { columnName: channel, columnType: string }
      - { columnName: site_cat1, columnType: string }
      - { columnName: site_cat2, columnType: string }
      - { columnName: return_reason_internal, columnType: string }
      - { columnName: return_reason_display, columnType: string }
      - { columnName: returned_to_stock, columnType: string }
      - { columnName: refund_amount, columnType: double }
      - { columnName: currency_code, columnType: string }
      - { columnName: return_shipping_cost, columnType: double }
      - { columnName: returned_to_store, columnType: string }

  - id: feedOrderLines
    jobName: feedOrderLinesV4
    description: "This feed contains order line information by order. This could include shipment information, sales/sales excluding tax, and delivery/shipment/promise timestamp lines.  It also contains several inventory flags to identify backorders, samples, free shipping, and order line attributes."
    schema:
      - { columnName: order_id, columnType: string }
      - { columnName: placed_timestamp, columnType: date }
      - { columnName: item_id, columnType: string }
      - { columnName: product_id, columnType: string }
      - { columnName: seller, columnType: string }
      - { columnName: quantity, columnType: integer }
      - { columnName: currency_code, columnType: string }
      - { columnName: sales, columnType: double }
      - { columnName: sales_ex_tax, columnType: double }
      - { columnName: promo_info, columnType: string }
      - { columnName: other_promo_cost, columnType: double }
      - { columnName: shipping_amount, columnType: double }
      - { columnName: shipping_ex_tax, columnType: double }
      - { columnName: shipping_cost, columnType: double }
      - { columnName: shipping_country, columnType: string }
      - { columnName: shipping_region, columnType: string }
      - { columnName: shipping_postal_code, columnType: string }
      - { columnName: shipping_method, columnType: string }
      - { columnName: delivery_location_type, columnType: string }
      - { columnName: shipment_promise_timestamp, columnType: date }
      - { columnName: delivery_promise_timestamp, columnType: date }
      - { columnName: pick_up_in_store_promise_timestamp, columnType: date }
      - { columnName: is_free_shipping, columnType: boolean }
      - { columnName: is_express_shipping, columnType: boolean }
      - { columnName: pick_pack_cost, columnType: double }
      - { columnName: is_backorder, columnType: boolean }
      - { columnName: is_preorder, columnType: boolean }
      - { columnName: is_ship_from_vendor, columnType: boolean }
      - { columnName: is_free_sample, columnType: boolean }
      - { columnName: unit_cost, columnType: float }
      - { columnName: current_price, columnType: float }
      - { columnName: full_price, columnType: float }
      - { columnName: price_currency_code, columnType: string }
      - { columnName: order_line_attribute1, columnType: string }
      - { columnName: order_line_attribute2, columnType: string }
      - { columnName: order_line_attribute3, columnType: string }
      - { columnName: order_line_attribute4, columnType: string }
      - { columnName: order_line_attribute5, columnType: string }

##  - id: feedDataAnalyticsImport
##    jobName: feedDataAnalyticsImportV4
##    description: "This feed is for loading historical metrics or prior period data."
##    schema:
##      - { columnName: startDate, columnType: date }
##      - { columnName: endDate, columnType: date }
##      - { columnName: metric_id, columnType: string }
##      - { columnName: metric_value, columnType: double }
##      - { columnName: dimensionList, columnType: string }
##      - { columnName: dimensionValues, columnType: string }

  - id: feedCalendar
    jobName: feedCalendarV4
    description: "This feed has the calendar information for the client's financial periods."
    schema:
      - { columnName: year, columnType: integer }
      - { columnName: quarter, columnType: integer }
      - { columnName: monthName, columnType: string }
      - { columnName: startDate, columnType: date }
      - { columnName: endDate, columnType: date }
      - { columnName: yearLabel, columnType: string }

##  - id: feedBusinessDays
##    jobName: feedBusinessDaysV4
##    description: "This feed contains the client business day lookups for shipping the calendar information for the client's financial periods."
##    schema:
##      - { columnName: date, columnType: date }
##      - { columnName: is_non_business_day, columnType: boolean }
##
##  - id: feedTrademarkTerms
##    jobName: feedTrademarkTermsV4
##    description: "This feed contains the client business day lookups for shipping the calendar information for the client's financial periods."
##    schema:
##      - { columnName: search_string, columnType: string }
##      - { columnName: longerThan3, columnType: string }
##
##
##  - id: feedCurrencyConversionRates
##    jobName: feedCurrencyConversionRatesV4
##    description: "This feed contains the client business day lookups for shipping the calendar information for the client's financial periods."
##    schema:
##      - { columnName: date, columnType: date }
##      - { columnName: currency_code, columnType: string }
##      - { columnName: conversion_rate, columnType: double }


