---
feedJobName: feedItemAttributesV4
feedOutput: feedItemAttributes
flows:

  - flowId: fragItemAttributesSegmentValue_Merge
    flowInputs:
      - fragItemAttributesSegmentValue
    schema:
      - { columnName: idx, columnType: integer }
      - { columnName: segmentId, columnType: string }
      - { columnName: value, columnType: string}
    flowSteps:
      - type: "AGGREGATE"
        logic: 
          aggregationColumns:
            - idx
            - segmentId
          aggregationOperations:
            - { columnName: value, operation: last() }


  - flowId: fragItemAttributesSegment_Merge
    flowInputs:
      - fragItemAttributesSegment
    schema:
      - { columnName: item_id, columnType: string }
      - { columnName: idx, columnType: integer }
      - { columnName: segmentId, columnType: string }
    flowSteps:
      - type: "AGGREGATE"
        logic: 
          aggregationColumns:
            - item_id
            - idx
          aggregationOperations:
            - { columnName: segmentId, operation: last() }


  - flowId: fragItemAttributesSegmentToValues_Join
    flowInputs:
      - fragItemAttributesSegmentValue_Merge
      - fragItemAttributesSegment_Merge
    schema:
      - { columnName: item_id, columnType: string }
      - { columnName: idx, columnType: integer }
      - { columnName: value, columnType: string }
    flowSteps:
      - type: "JOIN"
        logic:
          joinInputs: 
            - fragItemAttributesSegmentValue_Merge
            - fragItemAttributesSegment_Merge
          joinColumns:
            - idx
            - segmentId
          joinOperations:
            - { columnName: 'value' }



  - flowId: fragItemAttributes-Merge
    flowInputs:
      - fragItemAttributesSegmentToValues_Join
      - fragItemAttributes
    schema:
      - { columnName: item_id, columnType: string }
      - { columnName: idx, columnType: integer }
      - { columnName: value, columnType: string }
    flowSteps:
      - type: "AGGREGATE"
        logic: 
          aggregationColumns:
            - item_id
            - idx
          aggregationOperations:
            - { columnName: value, operation: last() }
